### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#1]
i am describing my issue here
[atrium sectional dimensions.pdf](https://github.com/elementdebase/site/files/307632/atrium.sectional.dimensions.pdf)
![strat noir et noyer](https://cloud.githubusercontent.com/assets/19843520/15940922/1a144944-2e4c-11e6-82c9-d362e6b2505e.jpg)

**Comment by elementdebase** [comment]
I am adding a comment to the test issue.

**Comment by elementdebase** [comment]
Closing becasue test ticket.

**Comment by minitachinita** [comment]
its ok

**Comment by minitachinita** [comment]
hjhklplpl

Date: Thu, 9 Jun 2016 11:12:47 -0700
