### ISSUE TITLE
waffle_ left color option

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#104]
la patch de couleur n'apparaît pas.
ça devrait montrer le Canavas Bourgogne 007

please make it show up again.
thanks
![waffle left - canevas bourgogne](https://cloud.githubusercontent.com/assets/19843520/16992426/3d5b4f6a-4e6d-11e6-868d-11eaed09dbca.png)

**Comment by AKRFranko** [comment]
It is because we only have one color. 

Note to self: I have to figure out the logic that differentiates these two things: 
- I am a product with only one option and I don't display a patch.
- I am a product with only one option and I display a patch.

**Comment by AKRFranko** [comment]
Will probably have to refresh page(s) to see changes (or use incognito to make sure). 
- Make sure: https://elementdebase.com/product/polka-purple_pilxxx16ad037d/ does NOT have a patch.
- Make sure: https://elementdebase.com/product/waffle_lftxxx08bc0276/ DOES have a patch
