### ISSUE TITLE
waffle_ right color option

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#105]
we should only see and be able to buy 
patch color : flannel anthracite 006
![waffle_right](https://cloud.githubusercontent.com/assets/19843520/16992958/6bd64e88-4e6f-11e6-9c04-2d3dc9f45afa.png)

**Comment by AKRFranko** [comment]
Will probably have to refresh page(s) to see changes (or use incognito to make sure). 
- Make sure: https://elementdebase.com/product/polka-purple_pilxxx16ad037d/ does NOT have a patch.
- Make sure: https://elementdebase.com/product/waffle_lftxxx08bc0276/ DOES have a patch
