### ISSUE TITLE
slope 1P

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#108]
please take out patch color : linen natural 002
no more in stock
![slope 1p - linen natural](https://cloud.githubusercontent.com/assets/19843520/16993425/5d5e9aca-4e71-11e6-9f2a-0ce98a4c3eb8.png)

**Comment by AKRFranko** [comment]
WAiting for #109 to be closed, or else I wont be able to select it in the order tool.

**Comment by minitachinita** [comment]
la cliente Anne Tremblay va prendre une livraison fin août,
voici son adresse et son courriel

A-3467 Simpson
Montreal, Qc
H3g 2J7

annetremb.design@gmail.com

**Comment by AKRFranko** [comment]
must fix #115 first.

**Comment by AKRFranko** [comment]
I think we dropped this?
