### ISSUE TITLE
testing order tool

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#109]
a designer ordered this :

1 x T-Table black $98.00
- discount 25%
  $73.50

1 x Slope armchair Linen natural 002
no discount (already on sale)
$290.00

can you prepare an invoice and send me what I will send out to the designer?

**Comment by AKRFranko** [comment]
I need at minimum email and postal code (email to make order valid and bound to a user, and postal code for proper shipping fees)

**Comment by AKRFranko** [comment]
unless it's self-pickup? The I still need an email address..

**Comment by AKRFranko** [comment]
fix #115 first.

**Comment by AKRFranko** [comment]
Alors je lui envoye?

**Comment by AKRFranko** [comment]
I think we dropped this?
