### ISSUE TITLE
sliders change 10 juin 2016

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#11]
A1 et A2

---

B1 - 
fr et en: t-table, $98.00
B2 - envoyer vers toutes les t-tables

---

C1 -
en : polka by paprika, $10.95
fr : polka par paprika, $10.95
C2- envoyer vers tous les coussins (et non juste les polka)

---

D1 et D2

---

E1- 
en : Maritime, modern classic revisited
fr : Maritime, un classique réinventé
E2 - envoyer vers tous les Maritime

**Comment by minitachinita** [comment]
![sliders_10-juin-2016_0000_d1](https://cloud.githubusercontent.com/assets/19843520/15950455/fe26039a-2e7c-11e6-9ba9-6188a51d759c.jpg)
![sliders_10-juin-2016_0000_e1](https://cloud.githubusercontent.com/assets/19843520/15950456/fe329bbe-2e7c-11e6-98c3-12e15b352910.jpg)
![sliders_10-juin-2016_0001_c1](https://cloud.githubusercontent.com/assets/19843520/15950457/fe37369c-2e7c-11e6-856c-77f2551e145c.jpg)
![sliders_10-juin-2016_0001_d2](https://cloud.githubusercontent.com/assets/19843520/15950458/fe3738b8-2e7c-11e6-84f7-f3e493d17bd6.jpg)
![sliders_10-juin-2016_0002_b1](https://cloud.githubusercontent.com/assets/19843520/15950461/fe38b576-2e7c-11e6-908c-345cb650940e.jpg)
![sliders_10-juin-2016_0005_a1](https://cloud.githubusercontent.com/assets/19843520/15950460/fe3867e2-2e7c-11e6-804c-7152af60b966.jpg)
![sliders_10-juin-2016_0006_a2](https://cloud.githubusercontent.com/assets/19843520/15950459/fe38403c-2e7c-11e6-92a4-b56f0e79e1b2.jpg)

**Comment by AKRFranko** [comment]
ya un petit probleme va falloir surement faire one comment per slide car les fichiers sont renomes alors j'ai difficulte a savoir quelle image est avec quel texte (github issue)

**Comment by AKRFranko** [comment]
J'ai surement bien devine polka, t-table et maritime.  J'ai pris les 2 sofas verts pour A1/A2 et les 2 plantes pour D1/D2... 

Si tout est beau, tu peut fermer le ticket sinon ecris mois les fix ici.
