### ISSUE TITLE
nouveau tissu 

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#149]
j'ai fait les images commes les autres,
c'est-à-dire une version 600 x600 et une autre 62 x 60
![fabric_0012_013](https://cloud.githubusercontent.com/assets/19843520/17445137/64e9d0d2-5b11-11e6-9174-9d9ce365148e.jpg)
![color13](https://cloud.githubusercontent.com/assets/19843520/17445210/c80adee0-5b11-11e6-85b1-498da7e2162d.jpg)

on a pas encore trouvé son nom.. mais ça s'en vient.
svp l'ajouter à la liste des matériaux.

**Comment by AKRFranko** [comment]
le nouveau tissu va s'appeler 
FLEECE GREY 014
FLEECE GRIS 014
