### ISSUE TITLE
sale price and check out price

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#156]
fais ce test et tu comprendras.

disons que tu veux un Martime 2-places Walnut,
tu vois que son prix de vente est de $750.00, tu le mets dans ton panier et
quand tu procèdes au check out, son prix affiché est le prix régulier de $895.00..

oups.

petit bug à arranger stp :)

**Comment by AKRFranko** [comment]
Had to review/update each product by hand. I hope I've got them all.

The procedure:  
- list sale products
- choose one
- add to cart
- view cart
- fix price if wrong
- remove from cart
- back to step 1
