### ISSUE TITLE
behavior from restocking to in stock

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#162]
exemple du PIQUE 94 LAF - 
variation 004 - tweed grey.

la date du restocking est passée, 
on avait mis pour le 15 août... 
and the website still shows it is in restocking 1 week...

est-ce qu'on peut lui dire que quand la date est passée, le restocking devient du stock!?

![capture d ecran 2016-08-16 a 18 54 24](https://cloud.githubusercontent.com/assets/19843520/17718582/be84c3fc-63e2-11e6-9230-8851f867be66.png)
![capture d ecran 2016-08-16 a 18 54 18](https://cloud.githubusercontent.com/assets/19843520/17718581/be81fe1a-63e2-11e6-99b5-a4f96ae6a4f6.png)

**Comment by AKRFranko** [comment]
note on calculation:

if -1 stock and 2 restock, stock becomes -1 + 2 = 1
if -1 stock and -1 restock, stock becomes -2
etc...

stock + restock = updatedstock
