### ISSUE TITLE
testing 3000 x1840

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#168]
![test 1500x920](https://cloud.githubusercontent.com/assets/19843520/17825309/a1fcc86a-6635-11e6-8a95-271d8a529e11.jpg)
![test 3000x1840](https://cloud.githubusercontent.com/assets/19843520/17825308/a1fca27c-6635-11e6-91fd-57d2744f2120.jpg)

**Comment by AKRFranko** [comment]
conclusion: same perceived blurryness on thien's iPad
