### ISSUE TITLE
alternative au ''mirroring''

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#175]
au lieu de continuer à travailler sur le ''mirroring'',
on pourrait se mettre à implanter le ''drop down menu'' ??

qu'est-ce que t'en penses?

**Comment by minitachinita** [comment]
drop down for leg options
Each leg options change the price. 

Ex : you get in MARITIME 3 seat

You can choose these legs options

Natural : price abc$
Walnut : price def$
Black metal : price ghi$
Brass
Chrome

**Comment by AKRFranko** [comment]
Makes sense.

**Comment by AKRFranko** [comment]
After discussions between @minitachinita  and myself we came to a solution.

Fixed by putting same product in 2 categories and adding special attributes to point to alternate images. Stock count is taken from single product but images taken from both.
