### ISSUE TITLE
ton avis sur IMAC

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#176]
voici les specs d'un imac usagé qu'on pourrait avoir :
iMac
Processeur: Intel Core i3, 3.1 GHz 
Hard Drive: 250GB 
Disk Drive: Apple SuperDrive (graveur DVD and CD) 
Mémoire: upgradé à 8 GB 
Écran: 21.5” LCD, 1920 x 1080 pixels 
Carte graphique: AMD Radeon HD 6750M with 256MB graphics memory 
Connections: Wi-Fi, Ethernet, 4 USB ports, 1 FireWire, 1 Mini DisplayPort, Audio In, Audio Out 

Peux-tu me dire ce que tu en penses?
Genre, est-ce qu'il répond à nos besoins à long terme?

Merci Franko!

**Comment by AKRFranko** [comment]
Not the best price. A Brand new is about $1300 and you need at least 16gb ram to run things like photoshop etc...
