### ISSUE TITLE
maritime tufted

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#179]
images à retoucher
![sofa_coast_001](https://cloud.githubusercontent.com/assets/19843520/18136951/8b80e6fa-6f74-11e6-9a71-fe477fd38f52.jpg)
![sofa_coast_002](https://cloud.githubusercontent.com/assets/19843520/18136952/8b812c00-6f74-11e6-8808-bef057fe2659.jpg)
![dsc_0597](https://cloud.githubusercontent.com/assets/19843520/18137029/d495a394-6f74-11e6-803e-3a50ded27545.JPG)

**Comment by elementdebase** [comment]
[ticket-179.zip](https://github.com/elementdebase/site/files/447873/ticket-179.zip)
