### ISSUE TITLE
promo code dans le listing

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#192]
fond de couleur 
RGB
204
102
102

**Comment by minitachinita** [comment]
centered dans l'image couleur : BACK15

title : Promo code
price : get 15% off regular items
description : 
GET 15% OFF OUR REGULAR PRICED ITEMS
one month only!
until sept 30th
use promo code:
back15

NEW COLOR!!! 
RGB
153
204
153

**Comment by AKRFranko** [comment]
APPROVED COLOR: rgba(204,204,153,1)

**Comment by minitachinita** [comment]
cool! cool! :)
il y a 2 fautes d'orthographe dans la version française

CODE PROMOTIONNEL 
(2 x n)

et ''à prix réguliers''
un accent sur le a

merci!
