### ISSUE TITLE
mettre le ''read'' sur la même ligne

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#201]
sinon, ça colle sur la ligne..
![capture d ecran 2016-09-21 a 15 37 20](https://cloud.githubusercontent.com/assets/19843520/18757496/254b3584-80c2-11e6-83c5-ff22b330f208.png)

**Comment by AKRFranko** [comment]
Je l'ai decolle, car dans #197 on le veut sur deux lignes.
