### ISSUE TITLE
Description pour Moonscape

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#217]
même description pour round and square
voici version anglaise et française

Moonscape tray 

Graphic & useful. Inspired by the craters of the moon, the small moulded Moonscape tray is made in a special resin giving it a look of stone or concrete. Handmade one by one, each tray is unique and shows signs of organic imperfections that add to its charm. Offered in round and square shapes the tray can be used for multiple purposes: key holder, coins collector, jewelry box or simply a pretty object sitting on a desk. You will certainly find a way to use it. 

Moonscape vide-poches

Graphique & utile. Inspiré des cratères lunaires, le petit vide-poche Moonscape est moulé dans une résine spéciale lui donnant une apparence de pierre ou de béton. Fabriqué un-à-un à la main, chaque vide-poche présente des traces d'imperfections organiques qui font son charme. Offert dans un format rond ou carré, il peut servir à recevoir des clés, des bijoux, de la monnaie, ou tout simplement servir d'élément visuel sur un bureau. Vous lui trouverez certainement un usage chez vous!

**Comment by AKRFranko** [comment]
Je savais pas trop quoi faire avec "Moonscape tray" et "Moonscape vide-poches" alros je les ai pas mis pour le moment.
