### ISSUE TITLE
3 new fabric

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#219]
![new-fabric-600x600_0000_pink-velvet](https://cloud.githubusercontent.com/assets/19843520/19001993/ecbce382-8717-11e6-929a-b4bef9494fc0.jpg)
![new-fabric-600x600_0001_light-grey-03](https://cloud.githubusercontent.com/assets/19843520/19001994/ecc27c16-8717-11e6-8ce3-d51e6ceeddd8.jpg)
![new-fabric-600x600_0002_dark-grey-06](https://cloud.githubusercontent.com/assets/19843520/19001995/ecc9c638-8717-11e6-9bae-bac0f7752526.jpg)

**Comment by AKRFranko** [comment]
Needs names (and descriptive details if available)
