### ISSUE TITLE
dans la section In the press (La Presse)

### ISSUE THREAD

**Issue by elementdebase** [elementdebase/site#230]
es-tu capable de retrouver ces petites images sur le web.
cahier maison du samedi 1er octobre 2016

(je met La Presse sur ton bureau)

**Comment by AKRFranko** [comment]
Pas trouve. La presse offre des abonnements en-ligne alors ils sont pas fort fort sur la "copie gratuite sur le web"

**Comment by elementdebase** [comment]
on prendra des photos alors

**Comment by elementdebase** [comment]
voilà. !
![img_1102_0000_lapresse_swivel01](https://cloud.githubusercontent.com/assets/19820985/19498002/e6a45f2c-955c-11e6-8c97-3f30030f683b.jpg)
![img_1102_0001_lapresse_swivel02](https://cloud.githubusercontent.com/assets/19820985/19498003/e6ac088a-955c-11e6-91c2-d07bdf7ef89c.jpg)
