### ISSUE TITLE
5 new fabrics 

### ISSUE THREAD

**Issue by elementdebase** [elementdebase/site#232]
Proof rust
Proof salmon 
composition : 100%  polyester

Tonic dark blue
Tonic dark grey
Tonic light grey
composition : leave blank (waiting for info)
![new-fabric-tonic-and-proof_0000_proof-rust](https://cloud.githubusercontent.com/assets/19820985/19159519/d5de3a10-8bba-11e6-85ec-fabcd53c246e.jpg)
![new-fabric-tonic-and-proof_0001_proof-salmon](https://cloud.githubusercontent.com/assets/19820985/19159523/d5f66aa4-8bba-11e6-8518-ac3b3ca39b17.jpg)
![new-fabric-tonic-and-proof_0002_tonic-light-grey](https://cloud.githubusercontent.com/assets/19820985/19159521/d5e24dda-8bba-11e6-88ac-490953d5131c.jpg)
![new-fabric-tonic-and-proof_0003_tonic-dark-grey](https://cloud.githubusercontent.com/assets/19820985/19159520/d5dec142-8bba-11e6-81b2-23fc82d24389.jpg)
![new-fabric-tonic-and-proof_0004_tonic-dark-blue](https://cloud.githubusercontent.com/assets/19820985/19159522/d5eac24e-8bba-11e6-8b6a-a043901696dc.jpg)

**Comment by AKRFranko** [comment]
Proof rust 025
Proof salmon 026

Tonic dark blue 027
Tonic dark grey 028
Tonic light grey 029
