### ISSUE TITLE
nouveau lookbook (atrium 2-seater)

### ISSUE THREAD

**Issue by elementdebase** [elementdebase/site#251]
Light hues

For this new photoshoot, we're in the mood for soft colors and neutral tones. Our white and black Insider tables stand by the Atrium 2-seater  in Tweed grey. Marble and rippled glass add textures to the setup. A light and breezy atmosphere for fall. 

Teintes douces

Pour cette nouvelle série d'images, nous avons envie de couleurs douces et de tons neutres. Le canapé Atrium 2-places en Tweed gris s'entoure de nos tables Insider,  en noir et blanc. La présence de marbre et de verre ondulé ajoute une profondeur au mélange des matières. Une atmosphère légère et aérée en ce début d'automne.

**Comment by elementdebase** [comment]
et voici les images
[export for web.zip](https://github.com/elementdebase/site/files/532082/export.for.web.zip)

**Comment by AKRFranko** [comment]
published and updated home page post.
