### ISSUE TITLE
Prepare a new landing page for free delivery

### ISSUE THREAD

**Issue by elementdebase** [elementdebase/site#264]
on préparera ça tantôt, ensemble

Prepare a new landing page for free delivery

Landing page : 
Title:
Free delivery on all your orders. 

For a limited time only, edb is offering free delivery on all your orders. 

At edb free delivery is standard for most sofas and furniture in Montreal, Quebec City, Toronto and Vancouver. 

Exceptionally, we are offering free delivery on any order, regardless of the value and the destination in Canada. 

Order by November 31st with the promo code : shipfree and enjoy free delivery on all your purchases. 

---

"Create a separation : maybe lots of white space, or a dotted line in the middle.."

Learn more about our shipping fees: 

Copy the whole section of the shipping info.... Here

**Comment by elementdebase** [comment]
version française

Version FR:

Landing page : 
Title
Livraison gratuite sur tous vos achats

Pour une durée limitée, edb vous offre la livraison gratuite sur tous vos achats en ligne.

Chez edb la livraison gratuite s'applique déjà automatiquement sur la plupart de nos canapés dans les régions de Montréal, Québec, Ottawa, Toronto ou Vancouver.

Exceptionnellement, nous offrons la livraison gratuite sur toutes les commandes peu importe le montant d'achat ou la destination. 

Commandez en ligne d'ici le 31 novembre avec le code promo : envoigratuit et profitez de la livraison gratuite sur tous vos achats. 

---

"Create a separation : maybe lots of white space, or a dotted line in the middle.."

Learn more about our shipping fees: 

Copy the whole section of the shipping info.... Here

**Comment by AKRFranko** [comment]
Link for page (with UTM codes.) 

https://goo.gl/lLN3lE
