### ISSUE TITLE
mailchimp letter to designer

### ISSUE THREAD

**Issue by elementdebase** [elementdebase/site#269]
je t'ai envoyé un draft de mailchimp.
j'ai inséré un bouton ''inscription ici'' 

pour l'instant, ça redirige vers la page trade and designers...

MAIS ça serait bon de créer une nouvelle landing page.
un formulaire tout simple.
(plus du style de la page ''échantillons''

nom, nom de compagnie, adresse,
champ d'activités, numéro de téléphone, etc...

quelque chose de simple que le designer a juste à rentrer l'info...

on en parle tantôt

**Comment by AKRFranko** [comment]
Sounds awesome!
