### ISSUE TITLE
new fabric Proof Chocolate

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#287]
PROOF CHOCOLAT
composition 100% polyester
![new-fabric-600x600_0001_proof-chocolat](https://cloud.githubusercontent.com/assets/19843520/21571260/8b8f44b2-ce9b-11e6-89a5-b957ea539357.jpg)

**Comment by minitachinita** [comment]
non. mets plutôt cette photo
![new fabric 600x600_0001_proof chocolat](https://cloud.githubusercontent.com/assets/19843520/21571266/9e739a7e-ce9b-11e6-9a3f-45ae16019c99.jpg)

**Comment by AKRFranko** [comment]
030
