### ISSUE TITLE
nouveau lookbook (maritime sectional)

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#289]
version française
PETIT SECTIONNEL
Un lookbook spécialement conçu pour les petits espaces. Ici, nous mettons en scène le canapé Maritime et son ottoman pour créer un sectionnel mesurant tout juste 88" de long par 63" de profondeur. Agrémenté de tables d'appoint Insider, le sectionnel donne du tonus même aux pièces les plus exigües. 

version anglaise
SMALL SECTIONAL
A lookbook made for small spaces. Here we put on stage our Maritime sofa and its matching ottoman to create a compact sectional of just 88" long by 63" deep. Added to the mix are the Insider side tables which bring a fresh and modern vibe. Proof that small rooms don't have to be boring.

**Comment by minitachinita** [comment]
[maritime lookbook export for web.zip](https://github.com/elementdebase/site/files/700641/maritime.lookbook.export.for.web.zip)

**Comment by minitachinita** [comment]
voila les 10 photos

**Comment by AKRFranko** [comment]
On avait deja un draft. J'ai ajoutte le texte.
