### ISSUE TITLE
slider 12 janvier 2017

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#293]
voici l'ordre du Caroussel
1. Buying sofas
2. Insider 
3. Designed in Mtl
4. Maritime sectionnel
5. Slip cover
6. Capsule

**Comment by minitachinita** [comment]
[export for web.zip](https://github.com/elementdebase/site/files/702934/export.for.web.zip)

**Comment by AKRFranko** [comment]
Caroussel! 👍
