### ISSUE TITLE
sliders 20 janvier 2017

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#300]
voici les images identifiées.
![slider_19-janvier_0000_designed-in-mtl_001](https://cloud.githubusercontent.com/assets/19843520/22161169/3db8dce4-df17-11e6-9e39-c07971fb323e.jpg)
![slider_19-janvier_0001_designed-in-mtl_002](https://cloud.githubusercontent.com/assets/19843520/22161172/3dc7044a-df17-11e6-8782-dfbedca02ea5.jpg)
![Uploading slider_19-janvier_0002_buying-sofa_001.jpg…]()
![slider_19-janvier_0003_buying-sofa_002](https://cloud.githubusercontent.com/assets/19843520/22161171/3dc3f9a8-df17-11e6-8bda-c2d55f325dcb.jpg)
![Uploading slider_19-janvier_0004_produit-dive-.jpg…]()
![Uploading slider_19-janvier_0005_produit-pique.jpg…]()

**Comment by AKRFranko** [comment]
1. les uploads on pas finis dans le ticket (il manque des images)
2. quand on upload dans le ticket le nom est perdu. ex: https://cloud.githubusercontent.com/assets/19843520/22161169/3db8dce4-df17-11e6-9e39-c07971fb323e.jpg
