### ISSUE TITLE
add 3 new blogposts (new rythme)

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#33]
on va essayer ceci.
voir preview ci-joint.

on utilise une image horizontal, suivie d'une image vertical (exactement 2 x la grandeur de l'image horizontale). les anciens blogposts vont bouger automatiquement..
![new blogpost rythme](https://cloud.githubusercontent.com/assets/19843520/16249772/5fa27d70-37e6-11e6-8ac8-4cf82f13de54.jpg)

**Comment by AKRFranko** [comment]
Je vais commence par supporter le nouveau format, ensuite aurai besoin de plus de details concernant " les anciens blogposts vont bouger automatiquement."
