### ISSUE TITLE
code promo et crédit

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#52]
how does Aline uses her $100 credit?‏
(accumulation de crédit dans son compte?)

**Comment by AKRFranko** [comment]
Good question. For now, we have to do it manually. (Ie: add a discount via order tool) But i have a solution to propose:
- We can only do this non-manually for a user who is registered and is logged-in during checkout.
- when user is at step where we ask for coupon, we add another field with total credits, where user select amount of credits to use.
- upon successful checkout, the amount is removed from cost and removed from total credits

**Comment by AKRFranko** [comment]
Closing this and creating new ticket for things left to do... see: #76
