### ISSUE TITLE
oups. addition de 2 coupons..

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#54]
est-ce que c'est possible de mettre maximum 1 coupon code par transaction !?
dans le printscreen ci-joint, on voit que 2 coupons ont été additionnés, totalisant une escompte de 30%!

![addition de 2 coupons code](https://cloud.githubusercontent.com/assets/19843520/16461121/019cc23a-3df9-11e6-89cd-37e72c2a3145.png)

**Comment by AKRFranko** [comment]
NB: udpate all exising coupons

**Comment by AKRFranko** [comment]
NB: all coupons should only apply to sale items.

**Comment by minitachinita** [comment]
do you mean ''all coupons should only apply to REGULAR items''??

**Comment by AKRFranko** [comment]
YEs.
