### ISSUE TITLE
items on sale 

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#55]
pour sectionnel WAFFLE right, svp, enlever la patch de tissu EPINGLE GRIS 005.

est-ce que c'est possible pour les items en vente de faire disparaître la patch de tissus quand l'inventaire est à zéro! on ne veut pas avoir à en recommander d'autres.. the ''16 weeks'' option should not be available...

sinon, on fera à la petite mitaine..
thks

**Comment by AKRFranko** [comment]
Je crois c'est mieux a la mitenne pour le peut de sale items qu'on a, sera plus vite que modifier le code pour appuyer ceci. Mains on peut y revenir dans le futur pour automatiser.
