### ISSUE TITLE
new product - Vintage table black

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#61]
please put these images dans l'ordre de 001 à 009
même wireframe que vintage white
same price
same availability
[vintage black.zip](https://github.com/elementdebase/site/files/342357/vintage.black.zip)

**Comment by AKRFranko** [comment]
stock qty?

**Comment by minitachinita** [comment]
put 30

**Comment by AKRFranko** [comment]
Hey, we have no en/fr descriptions for Vintage. See: #65
