### ISSUE TITLE
tamtam availability

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#67]
on the website it says : 1 week
on the client's order it says : 2 week

I don't know why..

**Comment by AKRFranko** [comment]
Which order number? So i can poke around.

**Comment by minitachinita** [comment]
order number 8725

**Comment by AKRFranko** [comment]
Some meta data needed on products to calculate these dates during generation of order did not exist for older items in our catalog (we added this information recently), so the fallback value was "+2 weeks" I changed the fallback value to "+1 week"
