### ISSUE TITLE
sales pages 1 and 2

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#79]
quand je clique sur le numéro 2 pour aller à la page 2,
ça me refresh la page 1...

je crois qu'il manque Slope 1P, il serait sur page 2 j'imagine..
![page 2 missing](https://cloud.githubusercontent.com/assets/19843520/16631507/7f035cb8-438d-11e6-8a42-077888163c62.png)

**Comment by AKRFranko** [comment]
fixed by making sale items not paged.
