### ISSUE TITLE
sliders 8 juillet 2016

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#90]
A1 et A2

---

B1 - 
fr : Panorama, ouverture, fluidité et courbes
$1,760.00 magasinez
en : Panorama, openness and curves
$1,760.00 shop now

B2- send to all Panorama

---

C1

---

D1 et D2

---

E1 - 
fr : Capsule, tout petit
$445.00 magasinez
en : Capsule, mini and practical
$445.00 shop now

E2 - vers Capsule
[export for web.zip](https://github.com/elementdebase/site/files/354827/export.for.web.zip)

**Comment by AKRFranko** [comment]
Bon, c'etais long je pouvais plus uploader d'images, ai du restarter le serveur...

**Comment by minitachinita** [comment]
tout est beau!! :)
lâches pas la patata!

sliders and sale all good ! thks 👍
