### ISSUE TITLE
promo code de chaque client

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#92]
comme on en a discuté, le promo code de ''Aline15'', par exemple, ne donnera pas de 15% d'escompte à son utilisateur sur les items déjà soldés. PAR CONTRE, on aimerait quand même donner à Aline un crédit de 10% sur la commande soldée..

Par exemple, si un ami à Aline achète un Waffle à $1095.00, lors du check out, il tape le promo code de Aline15 et comprend qu'il n'aura pas de 15% d'escompte additionnel. Par contre, on aimerait que Aline reçoive quand même $109.50 de crédit edb! Tu me suis? :P

Personne ne verrait cette information, ça serait dans le back stage.. et dans le compte crédit edb de Aline!

**Comment by AKRFranko** [comment]
Alors aline a un credit de 10% et son ami n'aura aucun rabais sur sa commande?

**Comment by minitachinita** [comment]
exactement!

**Comment by AKRFranko** [comment]
Ok, reste juste #76, #98 a faire...
