### ISSUE TITLE
in the press 1

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#94]
svp, trouver le logo de ce magazine. et si possible, aussi le cover du magazine, august 2016.
je ne veux pas scanner la version qu'on a car on voit que c'est envoyer à Thien Ta Trun, etc..

et mettre en lien cette image..
![canadian house and home august 2016](https://cloud.githubusercontent.com/assets/19843520/16812310/83be2c48-48fa-11e6-8149-a363014e4059.JPG)
![tamtam canadian house and home aug 2016](https://cloud.githubusercontent.com/assets/19843520/16812395/df5aabee-48fa-11e6-9314-725c703c8ec7.jpg)

pour le début du texte, ya les revues sur ta table...

**Comment by AKRFranko** [comment]
Jai vais un lien vers les back-issues sur leur site.

**Comment by AKRFranko** [comment]
changed to iamge
