### ISSUE TITLE
in the press 2

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#95]
et maintenant, 
Maison et Demeure juin 2016
![maison et demeure juin 2016](https://cloud.githubusercontent.com/assets/19843520/16812453/28e9e630-48fb-11e6-9fd2-05fe6fdc747a.JPG)
![tamtam maison et demeure juin 2016](https://cloud.githubusercontent.com/assets/19843520/16812553/9e97cece-48fb-11e6-8f2c-a180ee5e66ae.jpg)

**Comment by AKRFranko** [comment]
Jai vais un lien vers les back-issues sur leur site.

**Comment by AKRFranko** [comment]
changed to iamge
