### ISSUE TITLE
tamtam ''2 weeks''

### ISSUE THREAD

**Issue by minitachinita** [elementdebase/site#96]
on the website, it says 1 week, which is good 👍 
but on the order, it still shows ''2 weeks''

see attached image
![img_0074](https://cloud.githubusercontent.com/assets/19843520/16815653/aebf676e-4908-11e6-9f72-cffd9938e451.JPG)

**Comment by AKRFranko** [comment]
if _edb_variation_available_delay was not set it would fallback to +2weeks instead of checking _edb_available_delay first.
